## BFGS
- Implement the <b>BFGS</b> as a function and find the minimum of the following function:
    - $𝒇(𝒙)=𝒙^𝟐+y^2$
    - $𝒇(𝒙)=𝒙^𝟐+xy+y^2$  
    - $𝒇(𝒙)=𝒙^𝟐y$ 
- The stop condition is grad < epsilon.
- Try different epsilons and initial conditions.
- Compare the results from Gradient descent and Newton's method.

In [11]:
import numpy as np

In [41]:
def bfgs(alpha,x1,x0, eps):
    d = len(x0) # dimensions of the problem
    A0 = np.asarray(x0)
    A1 = np.asarray(x1)
    
    I = np.eye(d, dtype=int)
    B_inv = I
    for i in range(1000):
        DfA0 = np.array((Dfx(A0), Dfy(A0))) # initial gradient
        DfA1 = np.array((Dfx(A1), Dfy(A1))) # initial gradient

        print(f'xn_1: {A0} \nxn: {A1}')
        print(f'Dxn_1: {np.array([Dfx(A0), Dfy(A0)])} \nDxn: {np.array([Dfx(A1), Dfy(A1)])}')
        print(np.linalg.norm(DfA1))
        print('*****')
        
        delta_x = A1 - A0
        delta_y = DfA1 - DfA0
        
        ro = 1.0 / (np.dot(delta_y, delta_x))
        q1 = I - ro * delta_x[:, np.newaxis] * delta_y[np.newaxis, :]
        q2 = I - ro * delta_y[:, np.newaxis] * delta_x[np.newaxis, :]
        B_inv = np.dot(q1, np.dot(B_inv, q2)) + (ro * delta_x[:, np.newaxis] *
                                           delta_x[np.newaxis, :])
        
        #B_inv = np.dot(I - ((delta_x*delta_y) / np.dot(delta_y, delta_x)), np.dot(B_inv, I - ((delta_y*delta_x) / np.dot(delta_y, delta_x)) )) + ((delta_x*delta_x) / np.dot(delta_y, delta_x))
        res = np.array([A1, DfA1]).reshape(-1,2)
        
        A0 = A1
        A1 = A1 - alpha * np.dot(B_inv, DfA1)
        
        if np.linalg.norm(DfA1) < eps:
            
            print('Converged!')
            break
        print(f'B_inv: {B_inv}')
        print('*****************')
    return i , res

In [42]:
#first function
f = lambda A: A[0]**2 + A[1]**2
Dfx = lambda A: 2*A[0] 
Dfy = lambda A: 2*A[1]
DDfx = lambda A: 2
DDfy = lambda A: 2
DDfxy = lambda A: 0
DDfyx = lambda A: 0

In [43]:
## First function
## BFGD with xk-1 = (10,10) and x0 = (9,9), epsilon = 0.001
i , res = bfgs(1,(9,9),(10,10), 0.001)
print(f'Found solution after {i} iterations.')
print(res)

xn_1: [10 10] 
xn: [9 9]
Dxn_1: [20 20] 
Dxn: [18 18]
25.45584412271571
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [9 9] 
xn: [0. 0.]
Dxn_1: [18 18] 
Dxn: [0. 0.]
0.0
*****
Converged!
Found solution after 1 iterations.
[[0. 0.]
 [0. 0.]]


In [44]:
## First function
## BFGD with xk-1 = (10,10) and x0 = (9,9), epsilon = 0.001, 
## learning rate =0.9
i , res = bfgs(0.9,(9,9),(10,10), 0.001)
print(f'Found solution after {i} iterations.')
print(res)

xn_1: [10 10] 
xn: [9 9]
Dxn_1: [20 20] 
Dxn: [18 18]
25.45584412271571
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [9 9] 
xn: [0.9 0.9]
Dxn_1: [18 18] 
Dxn: [1.8 1.8]
2.545584412271572
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [0.9 0.9] 
xn: [0.09 0.09]
Dxn_1: [1.8 1.8] 
Dxn: [0.18 0.18]
0.25455844122715704
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [0.09 0.09] 
xn: [0.009 0.009]
Dxn_1: [0.18 0.18] 
Dxn: [0.018 0.018]
0.025455844122715694
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [0.009 0.009] 
xn: [0.0009 0.0009]
Dxn_1: [0.018 0.018] 
Dxn: [0.0018 0.0018]
0.0025455844122715702
*****
B_inv: [[ 0.75 -0.25]
 [-0.25  0.75]]
*****************
xn_1: [0.0009 0.0009] 
xn: [9.e-05 9.e-05]
Dxn_1: [0.0018 0.0018] 
Dxn: [0.00018 0.00018]
0.00025455844122715686
*****
Converged!
Found solution after 5 iterations.
[[9.0e-05 9.0e-05]
 [1.8e-04 1.8e-04]]


In [45]:
# second function
f = lambda A: A[0]**2 + A[0]*A[1] + A[1]**2
Dfx = lambda A: 2*A[0] + A[1]
DDfx = lambda A: 2
DDfxy = lambda A: 1

Dfy = lambda A: A[0] + 2*A[1]
DDfy = lambda A: 2
DDfyx = lambda A: 1


In [46]:
## Second function
## BFGD with xk-1 = (10,10) and x0 = (9,9), epsilon = 0.001
i , res = bfgs(1,(9,9),(10,10), 0.001)
print(f'Found solution after {i} iterations.')
print(res)

xn_1: [10 10] 
xn: [9 9]
Dxn_1: [30 30] 
Dxn: [27 27]
38.18376618407357
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [9 9] 
xn: [1.77635684e-15 1.77635684e-15]
Dxn_1: [27 27] 
Dxn: [5.32907052e-15 5.32907052e-15]
7.53644380168212e-15
*****
Converged!
Found solution after 1 iterations.
[[1.77635684e-15 1.77635684e-15]
 [5.32907052e-15 5.32907052e-15]]


In [47]:
## Second function
## BFGD with xk-1 = (10,10) and x0 = (9,9), epsilon = 0.001,
## learning rate  = 0.9
i , res = bfgs(0.9,(9,9),(10,10), 0.001)
print(f'Found solution after {i} iterations.')
print(res)

xn_1: [10 10] 
xn: [9 9]
Dxn_1: [30 30] 
Dxn: [27 27]
38.18376618407357
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [9 9] 
xn: [0.9 0.9]
Dxn_1: [27 27] 
Dxn: [2.7 2.7]
3.8183766184073655
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [0.9 0.9] 
xn: [0.09 0.09]
Dxn_1: [2.7 2.7] 
Dxn: [0.27 0.27]
0.381837661840737
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [0.09 0.09] 
xn: [0.009 0.009]
Dxn_1: [0.27 0.27] 
Dxn: [0.027 0.027]
0.038183766184073605
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [0.009 0.009] 
xn: [0.0009 0.0009]
Dxn_1: [0.027 0.027] 
Dxn: [0.0027 0.0027]
0.0038183766184073484
*****
B_inv: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
*****************
xn_1: [0.0009 0.0009] 
xn: [9.e-05 9.e-05]
Dxn_1: [0.0027 0.0027] 
Dxn: [0.00027 0.00027]
0.00038183766184073526
*****
Converged!
Fo

In [48]:
# third function
f = lambda A: A[0]**2 * A[1]
Dfx = lambda A: 2 * A[1] * A[0]
DDfxy = lambda A: 2 * A[0]
DDfx = lambda A: 2 * A[1]

Dfy = lambda A: A[0] ** 2
DDfyx = lambda A: 2 * A[0]
DDfy = lambda A: 0

In [49]:
## Third function
## BFGD with xk-1 = (10,10) and x0 = (9,9), epsilon = 0.001
i , res = bfgs(1,(9,9),(10,10), 0.001)
print(f'Found solution after {i} iterations.')
print(res)

xn_1: [10 10] 
xn: [9 9]
Dxn_1: [200 100] 
Dxn: [162  81]
181.12150617748296
*****
B_inv: [[ 0.23976608 -0.42690058]
 [-0.42690058  0.90643275]]
*****************
xn_1: [9 9] 
xn: [4.73684211 4.73684211]
Dxn_1: [162  81] 
Dxn: [44.87534626 22.43767313]
50.172162376034116
*****
B_inv: [[ 0.24648787 -0.4201788 ]
 [-0.4201788   0.91315453]]
*****************
xn_1: [4.73684211 4.73684211] 
xn: [3.10344828 3.10344828]
Dxn_1: [44.87534626 22.43767313] 
Dxn: [19.2627824  9.6313912]
21.536445443220426
*****
B_inv: [[ 0.26473765 -0.40192901]
 [-0.40192901  0.93140432]]
*****************
xn_1: [3.10344828 3.10344828] 
xn: [1.875 1.875]
Dxn_1: [19.2627824  9.6313912] 
Dxn: [7.03125  3.515625]
7.861176483398023
*****
B_inv: [[ 0.28917749 -0.37748918]
 [-0.37748918  0.95584416]]
*****************
xn_1: [1.875 1.875] 
xn: [1.16883117 1.16883117]
Dxn_1: [7.03125  3.515625] 
Dxn: [2.7323326 1.3661663]
3.0548407181235544
*****
B_inv: [[ 0.33173333 -0.33493333]
 [-0.33493333  0.9984    ]]
**************