### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.


### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.



In [2]:
import numpy as np
from scipy.linalg import lu

LU decompostion:
* Ax = y
* (LU)x = y
* LM = y; then  M = (L^-1)y
* Ux = M; then x = (U^-1)M

Steps:

1. get M
2. get x

Checks:

1. A is already equal to LU
2. the order of the permuatation matrix P

In [23]:
def lu_decomposition(A,y, dim):
  P, L , U = lu(A)
  if not(P == np.identity(dim)).all():
    A = np.dot(P,A) # arrange A rows based on P rows
    y = np.dot(P,y)
    A = np.dot(P,A) # arrange A rows based on LU rows
    y = np.dot(P,y)
  if(A == np.dot(L, U)).all():
    #1. get M : M = (L^-1)y
    M = np.dot(np.linalg.inv(L), y)

    #2. get x : x = (U^-1)M
    x = np.dot(np.linalg.inv(U), M)
  else:
    print("LU is not equal A")
  return P, L, U, M , x

In [28]:
# Ex1
A = [[2,5],
     [1,2]]
y = [[21],
     [8]]
P, L, U, M , x = lu_decomposition(A,y, 2)

In [29]:
print(f"P: {P} \n\nL: {L} \n\nU:{U} \n\nM:{M} \n\nx:{x}")

P: [[1. 0.]
 [0. 1.]] 

L: [[1.  0. ]
 [0.5 1. ]] 

U:[[ 2.   5. ]
 [ 0.  -0.5]] 

M:[[21. ]
 [-2.5]] 

x:[[-2.]
 [ 5.]]


In [32]:
# Ex1 using np.linalg.solve()
x = np.linalg.solve(A, y)
print(f"x:{x}")

x:[[-2.]
 [ 5.]]


In [33]:
# to check the soution is correct
np.allclose(np.dot(A, x), y)

True

In [34]:
# Ex2
A = [[ 1,  1,  1],
     [ 4,  3, -1],
     [ 3,  5,  3]]
y = [[1],
     [6],
     [4]]
P, L, U, M , x = lu_decomposition(A,y, 3)

In [35]:
print(f"P: {P} \n\nL: {L} \n\nU:{U} \n\nM:{M} \n\nx:{x}")

P: [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 

L: [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]] 

U:[[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]] 

M:[[ 6.        ]
 [-0.5       ]
 [-0.45454545]] 

x:[[ 1. ]
 [ 0.5]
 [-0.5]]


In [36]:
# Ex2 using np.linalg.solve()
x = np.linalg.solve(A, y)
print(f"x:{x}")

x:[[ 1. ]
 [ 0.5]
 [-0.5]]


In [37]:
# to check the soution is correct
np.allclose(np.dot(A, x), y)

True